/**
 * Flutter generator (P3).
 *
 * Emits a single Dart file with a `StatelessWidget` that builds the
 * design using `Container`, `Row`, `Column`, `Text`, `Image.network`,
 * and `Stack` for absolute fallback.
 *
 * The output compiles against a vanilla Flutter project — no extra
 * packages required.
 */
import type { IRDocument, IRNode, AlignValue, JustifyValue } from '../ir/types';
import { CodeGenerator, GenerateResult } from './base';
import { pascalCase } from '../utils/tree';

function dartString(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;
}

function colorToDart(css: string | undefined): string | null {
  if (!css) return null;
  const hex = /^#([0-9a-f]{6})$/i.exec(css.trim());
  if (hex) return `Color(0xFF${hex[1].toUpperCase()})`;
  const hex8 = /^#([0-9a-f]{8})$/i.exec(css.trim());
  if (hex8) {
    // CSS is #rrggbbaa, Dart is 0xAARRGGBB
    const [_, h] = hex8;
    const aa = h.slice(6, 8);
    const rgb = h.slice(0, 6);
    return `Color(0x${aa.toUpperCase()}${rgb.toUpperCase()})`;
  }
  const rgba = /^rgba?\(([^)]+)\)$/i.exec(css.trim());
  if (rgba) {
    const parts = rgba[1].split(',').map((p) => p.trim());
    const r = parseInt(parts[0], 10);
    const g = parseInt(parts[1], 10);
    const b = parseInt(parts[2], 10);
    const a = parts[3] !== undefined ? parseFloat(parts[3]) : 1;
    const aa = Math.round(a * 255).toString(16).padStart(2, '0');
    const hh = (n: number) => n.toString(16).padStart(2, '0');
    return `Color(0x${aa.toUpperCase()}${hh(r).toUpperCase()}${hh(g).toUpperCase()}${hh(b).toUpperCase()})`;
  }
  return null;
}

const ALIGN_MAIN: Record<JustifyValue, string> = {
  start: 'MainAxisAlignment.start',
  center: 'MainAxisAlignment.center',
  end: 'MainAxisAlignment.end',
  'space-between': 'MainAxisAlignment.spaceBetween',
  'space-around': 'MainAxisAlignment.spaceAround',
  'space-evenly': 'MainAxisAlignment.spaceEvenly',
};

const ALIGN_CROSS: Record<AlignValue, string> = {
  start: 'CrossAxisAlignment.start',
  center: 'CrossAxisAlignment.center',
  end: 'CrossAxisAlignment.end',
  stretch: 'CrossAxisAlignment.stretch',
};

export class FlutterGenerator extends CodeGenerator {
  readonly platform = 'flutter';

  generate(doc: IRDocument): GenerateResult {
    const componentName = pascalCase(doc.name || 'GeneratedWidget');
    const body = this.renderNode(doc.root, 6);
    const file = `// Generated by d2c — Flutter
import 'package:flutter/material.dart';

class ${componentName} extends StatelessWidget {
  const ${componentName}({super.key});

  @override
  Widget build(BuildContext context) {
    return ${body.trimStart()};
  }
}
`;
    return {
      entryFile: `${this.snake(componentName)}.dart`,
      files: [{ path: `${this.snake(componentName)}.dart`, content: file }],
    };
  }

  private snake(s: string): string {
    return s.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
  }

  private renderNode(node: IRNode, indent: number, parentLayout?: 'flex' | 'grid' | 'absolute'): string {
    const pad = ' '.repeat(indent);
    const inner = ' '.repeat(indent + 2);

    if (node.type === 'image') {
      const src = node.assetRef ?? '';
      const w = typeof node.box.width === 'number' ? node.box.width : null;
      const h = typeof node.box.height === 'number' ? node.box.height : null;
      const r = typeof node.style.borderRadius === 'number' ? node.style.borderRadius : 0;
      const args: string[] = [];
      if (w !== null) args.push(`width: ${w}`);
      if (h !== null) args.push(`height: ${h}`);
      const img = `Image.network(${dartString(src)}${
        args.length ? ', ' + args.join(', ') + ', fit: BoxFit.cover' : ''
      })`;
      if (r > 0) {
        return `${pad}ClipRRect(\n${inner}borderRadius: BorderRadius.circular(${r}),\n${inner}child: ${img},\n${pad})`;
      }
      return `${pad}${img}`;
    }

    if (node.type === 'text' || node.textStyle) {
      const t = node.textStyle!;
      const styleProps: string[] = [`fontSize: ${t.fontSize}`];
      const c = colorToDart(t.color);
      if (c) styleProps.push(`color: ${c}`);
      styleProps.push(`fontWeight: FontWeight.w${t.fontWeight}`);
      if (t.lineHeight) styleProps.push(`height: ${(t.lineHeight / t.fontSize).toFixed(2)}`);
      const align =
        t.textAlign === 'center'
          ? ', textAlign: TextAlign.center'
          : t.textAlign === 'right'
            ? ', textAlign: TextAlign.right'
            : '';
      return `${pad}Text(\n${inner}${dartString(t.content)},\n${inner}style: TextStyle(${styleProps.join(', ')})${align ? ',' : ''}${align ? align.trimStart() : ''}\n${pad})`;
    }

    // Container-like
    const childrenWidget = this.renderChildrenWidget(node, indent + 2);
    const decoration = this.renderDecoration(node, indent + 2);
    const props: string[] = [];

    if (typeof node.box.width === 'number') props.push(`${inner}width: ${node.box.width},`);
    if (typeof node.box.height === 'number') props.push(`${inner}height: ${node.box.height},`);
    if (node.box.padding) {
      const [t, r, b, l] = node.box.padding;
      if (t === r && r === b && b === l)
        props.push(`${inner}padding: const EdgeInsets.all(${t}),`);
      else
        props.push(
          `${inner}padding: const EdgeInsets.fromLTRB(${l}, ${t}, ${r}, ${b}),`,
        );
    }
    if (decoration) props.push(`${inner}decoration: ${decoration},`);
    if (childrenWidget) props.push(`${inner}child: ${childrenWidget.trimStart()},`);

    return `${pad}Container(\n${props.join('\n')}\n${pad})`;
  }

  private renderDecoration(node: IRNode, indent: number): string | null {
    const pad = ' '.repeat(indent);
    const parts: string[] = [];
    const bg = colorToDart(node.style.backgroundColor);
    if (bg) parts.push(`color: ${bg}`);
    if (typeof node.style.borderRadius === 'number') {
      parts.push(`borderRadius: BorderRadius.circular(${node.style.borderRadius})`);
    }
    if (node.style.border) {
      const c = colorToDart(node.style.border.color) ?? 'Colors.black';
      parts.push(`border: Border.all(color: ${c}, width: ${node.style.border.width})`);
    }
    if (node.style.shadows?.length) {
      const sh = node.style.shadows[0];
      const sc = colorToDart(sh.color) ?? 'Colors.black26';
      parts.push(
        `boxShadow: [BoxShadow(color: ${sc}, offset: Offset(${sh.x}, ${sh.y}), blurRadius: ${sh.blur})]`,
      );
    }
    if (!parts.length) return null;
    return `BoxDecoration(\n${pad}  ${parts.join(',\n' + pad + '  ')},\n${pad})`;
  }

  private renderChildrenWidget(node: IRNode, indent: number): string | null {
    if (node.children.length === 0) return null;
    const childLayout = node.layout.type;
    if (node.children.length === 1) return this.renderNode(node.children[0], indent, childLayout);

    const pad = ' '.repeat(indent);
    const childPad = ' '.repeat(indent + 2);

    if (node.layout.type === 'flex') {
      const widget = node.layout.direction === 'column' ? 'Column' : 'Row';
      const args: string[] = [];
      if (node.layout.justifyContent && ALIGN_MAIN[node.layout.justifyContent]) {
        args.push(`mainAxisAlignment: ${ALIGN_MAIN[node.layout.justifyContent]}`);
      }
      if (node.layout.alignItems && ALIGN_CROSS[node.layout.alignItems]) {
        args.push(`crossAxisAlignment: ${ALIGN_CROSS[node.layout.alignItems]}`);
      }
      // Insert SizedBox between children for gap support
      const gap = node.layout.gap;
      const renderedChildren: string[] = [];
      for (let i = 0; i < node.children.length; i++) {
        renderedChildren.push(`${childPad}${this.renderNode(node.children[i], indent + 4, childLayout).trimStart()}`);
        if (gap && i < node.children.length - 1) {
          const sizedBox = node.layout.direction === 'column'
            ? `SizedBox(height: ${gap})`
            : `SizedBox(width: ${gap})`;
          renderedChildren.push(`${childPad}${sizedBox}`);
        }
      }
      const children = renderedChildren.join(',\n');
      const argLines = args.map((a) => `${childPad}${a},`).join('\n');
      return `${widget}(\n${argLines ? argLines + '\n' : ''}${childPad}children: [\n${children},\n${childPad}],\n${pad})`;
    }
    if (node.layout.type === 'grid') {
      const children = node.children
        .map((c) => this.renderNode(c, indent + 4, childLayout).trimStart())
        .map((s) => `${childPad}${s}`)
        .join(',\n');
      return `Wrap(\n${childPad}spacing: ${node.layout.gap ?? 0},\n${childPad}runSpacing: ${node.layout.gap ?? 0},\n${childPad}children: [\n${children},\n${childPad}],\n${pad})`;
    }
    // absolute fallback — wrap children in Positioned
    const children = node.children
      .map((c) => {
        const childWidget = this.renderNode(c, indent + 6, childLayout).trimStart();
        const x = c.box.x;
        const y = c.box.y;
        const posArgs = [`left: ${x}`, `top: ${y}`];
        return `${childPad}Positioned(\n${childPad}  ${posArgs.join(', ')},\n${childPad}  child: ${childWidget},\n${childPad})`;
      })
      .join(',\n');
    return `Stack(\n${childPad}children: [\n${children},\n${childPad}],\n${pad})`;
  }
}
