import type { IRDocument, IRNode, SemanticRole } from '../ir/types';
import { CodeGenerator, GenerateResult, GeneratedFile } from './base';
import { buildCssProps, cssPropsToBlock } from './cssBuilder';
import { kebabCase } from '../utils/tree';

const HTML_TAG_BY_ROLE: Partial<Record<SemanticRole, string>> = {
  header: 'header',
  nav: 'nav',
  footer: 'footer',
  main: 'main',
  aside: 'aside',
  section: 'section',
  card: 'article',
  list: 'ul',
  'list-item': 'li',
  button: 'button',
  link: 'a',
  heading: 'h2',
  paragraph: 'p',
  label: 'label',
};

function tagFor(node: IRNode): string {
  const role = node.semantics?.role;
  if (role && HTML_TAG_BY_ROLE[role]) return HTML_TAG_BY_ROLE[role]!;
  switch (node.type) {
    case 'text':
      return 'span';
    case 'image':
      return 'img';
    case 'icon':
      return 'span';
    case 'button':
      return 'button';
    case 'input':
      return 'input';
    case 'list':
      return 'ul';
    case 'list-item':
      return 'li';
    default:
      return 'div';
  }
}

export class HtmlGenerator extends CodeGenerator {
  readonly platform = 'html';
  private classIndex = new Map<string, string>();
  private classCss: string[] = [];
  private classCounter = 0;

  generate(doc: IRDocument): GenerateResult {
    this.classIndex.clear();
    this.classCss = [];
    this.classCounter = 0;

    const body = this.renderNode(doc.root, 4, undefined, { isRoot: true });
    const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${this.escapeText(doc.name)}</title>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
${body}
  </body>
</html>
`;

    const css = `/* Generated by d2c */
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; overflow-x: hidden; }
img { display: block; max-width: 100%; }

${this.classCss.join('\n\n')}
`;

    return {
      entryFile: 'index.html',
      files: [
        { path: 'index.html', content: html },
        { path: 'styles.css', content: css },
      ],
    };
  }

  // 多页面：每页一个独立 HTML + 共享导航
  generateMultiPage(docs: IRDocument[]): GenerateResult {
    if (docs.length === 1) return this.generate(docs[0]);
    const allFiles: GeneratedFile[] = [];
    const pageNames = docs.map((d, i) => ({
      name: d.name || `Page ${i + 1}`,
      file: `${this.safePageDir(d.name || `page_${i + 1}`)}.html`,
    }));

    for (let i = 0; i < docs.length; i++) {
      // 每页独立生成 CSS
      this.classIndex.clear();
      this.classCss = [];
      this.classCounter = 0;
      const body = this.renderNode(docs[i].root, 4, undefined, { isRoot: true });
      const navItems = pageNames
        .map((p, j) =>
          j === i
            ? `      <span style="font-weight:bold">${this.escapeText(p.name)}</span>`
            : `      <a href="${p.file}">${this.escapeText(p.name)}</a>`,
        )
        .join('\n');
      const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${this.escapeText(pageNames[i].name)}</title>
    <style>
.d2c-page-nav { display:flex; gap:16px; padding:12px 16px; background:#f5f5f5; border-bottom:1px solid #ddd; font-family:sans-serif; }
.d2c-page-nav a { text-decoration:none; color:#0066cc; }
${this.classCss.join('\n')}
    </style>
  </head>
  <body>
    <nav class="d2c-page-nav">
${navItems}
    </nav>
${body}
  </body>
</html>
`;
      allFiles.push({ path: pageNames[i].file, content: html });
    }

    return { files: allFiles, entryFile: pageNames[0].file };
  }

  private classFor(
    node: IRNode,
    parentLayout?: 'flex' | 'grid' | 'absolute',
    opts?: { parentDirection?: 'row' | 'column'; isRoot?: boolean },
  ): string {
    const props = buildCssProps(node, parentLayout, opts);
    const key = JSON.stringify(props);
    if (this.classIndex.has(key)) return this.classIndex.get(key)!;
    const base = kebabCase(node.semantics?.componentName || node.name || node.type);
    const name = `d2c-${base}-${++this.classCounter}`;
    this.classIndex.set(key, name);
    this.classCss.push(`.${name} {\n${cssPropsToBlock(props, 2)}\n}`);
    return name;
  }

  private renderNode(
    node: IRNode,
    indent: number,
    parentLayout?: 'flex' | 'grid' | 'absolute',
    opts?: { parentDirection?: 'row' | 'column'; isRoot?: boolean },
  ): string {
    const pad = ' '.repeat(indent);
    const tag = tagFor(node);
    const className = this.classFor(node, parentLayout, opts);

    // input 元素: 自闭合, 使用 placeholder 属性
    if (node.type === 'input') {
      const placeholder = this.escapeText(node.semantics?.ariaLabel ?? '');
      return `${pad}<input class="${className}" placeholder="${placeholder}" />`;
    }

    if (node.type === 'image') {
      const src = node.assetRef ?? '';
      const alt = this.escapeText(node.semantics?.ariaLabel ?? node.name);
      return `${pad}<img class="${className}" src="${src}" alt="${alt}" />`;
    }

    if (node.type === 'text' || node.textStyle) {
      const content = this.escapeText(node.textStyle?.content ?? '');
      return `${pad}<${tag} class="${className}">${content}</${tag}>`;
    }

    // 按钮等交互元素: 如果只有一个文本子节点, 将文本内联
    if ((tag === 'button' || tag === 'a') && node.children.length === 1 &&
        (node.children[0].type === 'text' || node.children[0].textStyle)) {
      const content = this.escapeText(node.children[0].textStyle?.content ?? '');
      return `${pad}<${tag} class="${className}">${content}</${tag}>`;
    }

    if (node.children.length === 0) {
      return `${pad}<${tag} class="${className}"></${tag}>`;
    }

    const childLayout = node.layout.type;
    const childDirection = node.layout.direction;
    const childrenHtml = node.children
      .map((c) => this.renderNode(c, indent + 2, childLayout, { parentDirection: childDirection }))
      .join('\n');
    return `${pad}<${tag} class="${className}">
${childrenHtml}
${pad}</${tag}>`;
  }
}
