import type { IRDocument, IRNode, SemanticRole } from '../ir/types';
import { CodeGenerator, GenerateResult } from './base';
import { buildCssProps, cssPropsToBlock } from './cssBuilder';
import { kebabCase } from '../utils/tree';

const HTML_TAG_BY_ROLE: Partial<Record<SemanticRole, string>> = {
  header: 'header',
  nav: 'nav',
  footer: 'footer',
  main: 'main',
  aside: 'aside',
  section: 'section',
  card: 'article',
  list: 'ul',
  'list-item': 'li',
  button: 'button',
  link: 'a',
  heading: 'h2',
  paragraph: 'p',
  label: 'label',
};

function tagFor(node: IRNode): string {
  const role = node.semantics?.role;
  if (role && HTML_TAG_BY_ROLE[role]) return HTML_TAG_BY_ROLE[role]!;
  switch (node.type) {
    case 'text':
      return 'span';
    case 'image':
      return 'img';
    case 'icon':
      return 'span';
    case 'button':
      return 'button';
    case 'input':
      return 'input';
    case 'list':
      return 'ul';
    case 'list-item':
      return 'li';
    default:
      return 'div';
  }
}

export class HtmlGenerator extends CodeGenerator {
  readonly platform = 'html';
  private classIndex = new Map<string, string>();
  private classCss: string[] = [];
  private classCounter = 0;

  generate(doc: IRDocument): GenerateResult {
    this.classIndex.clear();
    this.classCss = [];
    this.classCounter = 0;

    const body = this.renderNode(doc.root, 4);
    const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${this.escapeText(doc.name)}</title>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
${body}
  </body>
</html>
`;

    const css = `/* Generated by d2c */
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
img { display: block; max-width: 100%; }

${this.classCss.join('\n\n')}
`;

    return {
      entryFile: 'index.html',
      files: [
        { path: 'index.html', content: html },
        { path: 'styles.css', content: css },
      ],
    };
  }

  private classFor(node: IRNode, parentLayout?: 'flex' | 'grid' | 'absolute'): string {
    const props = buildCssProps(node, parentLayout);
    const key = JSON.stringify(props);
    if (this.classIndex.has(key)) return this.classIndex.get(key)!;
    const base = kebabCase(node.semantics?.componentName || node.name || node.type);
    const name = `d2c-${base}-${++this.classCounter}`;
    this.classIndex.set(key, name);
    this.classCss.push(`.${name} {\n${cssPropsToBlock(props, 2)}\n}`);
    return name;
  }

  private renderNode(node: IRNode, indent: number, parentLayout?: 'flex' | 'grid' | 'absolute'): string {
    const pad = ' '.repeat(indent);
    const tag = tagFor(node);
    const className = this.classFor(node, parentLayout);

    if (node.type === 'image') {
      const src = node.assetRef ?? '';
      const alt = this.escapeText(node.semantics?.ariaLabel ?? node.name);
      return `${pad}<img class="${className}" src="${src}" alt="${alt}" />`;
    }

    if (node.type === 'text' || node.textStyle) {
      const content = this.escapeText(node.textStyle?.content ?? '');
      return `${pad}<${tag} class="${className}">${content}</${tag}>`;
    }

    if (node.children.length === 0) {
      return `${pad}<${tag} class="${className}"></${tag}>`;
    }

    const childLayout = node.layout.type;
    const childrenHtml = node.children
      .map((c) => this.renderNode(c, indent + 2, childLayout))
      .join('\n');
    return `${pad}<${tag} class="${className}">
${childrenHtml}
${pad}</${tag}>`;
  }
}
