/**
 * React Native generator (P3).
 *
 * Emits a single .tsx file using `View` / `Text` / `Image` /
 * `Pressable` from `react-native`, plus a `StyleSheet.create` block.
 *
 * - No Tailwind / className — RN uses style objects.
 * - Layouts map naturally: flex/row/column → flexbox is the RN default.
 * - Absolute fallback uses `position: 'absolute'` with raw left/top.
 */
import type { IRDocument, IRNode } from '../ir/types';
import { CodeGenerator, GenerateResult } from './base';
import { pascalCase } from '../utils/tree';

interface RNStyle {
  [key: string]: string | number;
}

function safeIdent(name: string, idx: number): string {
  const s = name.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^[0-9]/, '_$&');
  return /^[A-Za-z_]/.test(s) ? `${s.charAt(0).toLowerCase()}${s.slice(1)}_${idx}` : `s_${idx}`;
}

function tagFor(node: IRNode): { tag: string; isText: boolean } {
  if (node.type === 'image') return { tag: 'Image', isText: false };
  if (node.type === 'text' || node.textStyle) return { tag: 'Text', isText: true };
  if (node.type === 'button' || node.semantics?.role === 'button')
    return { tag: 'Pressable', isText: false };
  return { tag: 'View', isText: false };
}

function escapeJsx(s: string): string {
  return s.replace(/\{/g, '&#123;').replace(/\}/g, '&#125;').replace(/</g, '&lt;');
}

export class ReactNativeGenerator extends CodeGenerator {
  readonly platform = 'react-native';
  private styles = new Map<string, { name: string; props: RNStyle }>();
  private counter = 0;

  generate(doc: IRDocument): GenerateResult {
    this.styles.clear();
    this.counter = 0;
    const componentName = pascalCase(doc.name || 'GeneratedComponent');
    const body = this.renderNode(doc.root, 4);

    const importsUsed = this.collectImports(doc.root);
    const importLine = `import { ${[...importsUsed].sort().join(', ')}, StyleSheet } from 'react-native';`;

    const styleEntries = [...this.styles.values()].map(
      (s) => `  ${s.name}: ${this.renderStyleObj(s.props, 4)},`,
    );

    const tsx = `// Generated by d2c — React Native
import React from 'react';
${importLine}

export interface ${componentName}Props {}

export const ${componentName}: React.FC<${componentName}Props> = () => {
  return (
${body}
  );
};

const styles = StyleSheet.create({
${styleEntries.join('\n')}
});

export default ${componentName};
`;

    return {
      entryFile: `${componentName}.tsx`,
      files: [{ path: `${componentName}.tsx`, content: tsx }],
    };
  }

  private collectImports(root: IRNode): Set<string> {
    const used = new Set<string>(['View']);
    const visit = (n: IRNode) => {
      const { tag } = tagFor(n);
      used.add(tag);
      for (const c of n.children) visit(c);
    };
    visit(root);
    return used;
  }

  private renderStyleObj(props: RNStyle, indent: number): string {
    const pad = ' '.repeat(indent);
    const inner = ' '.repeat(indent + 2);
    const lines: string[] = [];
    const skip = new Set(['__shadowOffsetW', '__shadowOffsetH']);
    for (const [k, v] of Object.entries(props)) {
      if (skip.has(k)) continue;
      const val =
        typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "\\'")}'`;
      lines.push(`${inner}${k}: ${val},`);
    }
    if (props.__shadowOffsetW !== undefined || props.__shadowOffsetH !== undefined) {
      const w = Number(props.__shadowOffsetW ?? 0);
      const h = Number(props.__shadowOffsetH ?? 0);
      lines.push(`${inner}shadowOffset: { width: ${w}, height: ${h} },`);
    }
    return `{\n${lines.join('\n')}\n${pad}}`;
  }

  private styleFor(node: IRNode): string {
    const props = this.buildStyle(node);
    const key = JSON.stringify(props);
    const existing = this.styles.get(key);
    if (existing) return existing.name;
    const name = safeIdent(node.semantics?.componentName || node.name || node.type, ++this.counter);
    this.styles.set(key, { name, props });
    return name;
  }

  private buildStyle(node: IRNode): RNStyle {
    const s: RNStyle = {};
    const { box, layout, style, textStyle } = node;
    if (typeof box.width === 'number') s.width = Math.round(box.width);
    if (typeof box.height === 'number') s.height = Math.round(box.height);
    if (box.padding) {
      const [t, r, b, l] = box.padding;
      if (t === r && r === b && b === l) s.padding = t;
      else {
        s.paddingTop = t;
        s.paddingRight = r;
        s.paddingBottom = b;
        s.paddingLeft = l;
      }
    }

    if (layout.type === 'flex') {
      s.flexDirection = layout.direction === 'column' ? 'column' : 'row';
      if (layout.gap) s.gap = layout.gap;
      const aiMap: Record<string, string> = {
        start: 'flex-start',
        center: 'center',
        end: 'flex-end',
        stretch: 'stretch',
      };
      const jcMap: Record<string, string> = {
        start: 'flex-start',
        center: 'center',
        end: 'flex-end',
        'space-between': 'space-between',
        'space-around': 'space-around',
        'space-evenly': 'space-evenly',
      };
      if (layout.alignItems) s.alignItems = aiMap[layout.alignItems];
      if (layout.justifyContent) s.justifyContent = jcMap[layout.justifyContent];
    } else if (layout.type === 'grid') {
      // RN has no grid; fallback to row + wrap
      s.flexDirection = 'row';
      s.flexWrap = 'wrap';
      if (layout.gap) s.gap = layout.gap;
    } else if (layout.type === 'absolute') {
      s.position = 'relative';
    }

    if (style.backgroundColor) s.backgroundColor = style.backgroundColor;
    if (typeof style.borderRadius === 'number') s.borderRadius = style.borderRadius;
    if (style.border) {
      s.borderWidth = style.border.width;
      s.borderColor = style.border.color;
    }
    if (style.opacity !== undefined && style.opacity < 1) s.opacity = style.opacity;
    if (style.shadows && style.shadows.length) {
      const sh = style.shadows[0];
      s.shadowColor = sh.color;
      // shadowOffset rendered as a literal object in renderStyleObj
      s.__shadowOffsetW = sh.x;
      s.__shadowOffsetH = sh.y;
      s.shadowRadius = sh.blur;
      s.shadowOpacity = 0.2;
      s.elevation = Math.max(2, Math.round(sh.blur / 2));
    }
    if (textStyle) {
      s.fontSize = textStyle.fontSize;
      s.fontWeight =
        (textStyle.fontWeight as unknown as string) === '400'
          ? 'normal'
          : String(textStyle.fontWeight);
      s.color = textStyle.color;
      if (textStyle.textAlign) s.textAlign = textStyle.textAlign;
      if (textStyle.lineHeight) s.lineHeight = textStyle.lineHeight;
    }
    return s;
  }

  private renderNode(node: IRNode, indent: number): string {
    const pad = ' '.repeat(indent);
    const { tag, isText } = tagFor(node);
    const styleName = this.styleFor(node);
    const styleAttr = ` style={styles.${styleName}}`;

    if (tag === 'Image') {
      const src = node.assetRef ?? '';
      return `${pad}<Image source={{ uri: '${src}' }}${styleAttr} />`;
    }
    if (isText) {
      const content = escapeJsx(node.textStyle?.content ?? '');
      return `${pad}<Text${styleAttr}>${content}</Text>`;
    }
    if (node.children.length === 0) {
      return `${pad}<${tag}${styleAttr} />`;
    }
    const children = node.children.map((c) => this.renderNode(c, indent + 2)).join('\n');
    return `${pad}<${tag}${styleAttr}>
${children}
${pad}</${tag}>`;
  }
}
