/**
 * React + Tailwind CSS generator.
 *
 * Uses arbitrary-value Tailwind classes (e.g. `w-[240px]`) so the output
 * doesn't require any design-system pre-configuration to compile.
 */
import type { IRDocument, IRNode, SemanticRole } from '../ir/types';
import { CodeGenerator, GenerateResult } from './base';
import { pascalCase } from '../utils/tree';

const HTML_TAG_BY_ROLE: Partial<Record<SemanticRole, string>> = {
  header: 'header',
  nav: 'nav',
  footer: 'footer',
  main: 'main',
  aside: 'aside',
  section: 'section',
  card: 'article',
  list: 'ul',
  'list-item': 'li',
  button: 'button',
  link: 'a',
  heading: 'h2',
  paragraph: 'p',
  label: 'label',
};

function tagFor(node: IRNode): string {
  const role = node.semantics?.role;
  if (role && HTML_TAG_BY_ROLE[role]) return HTML_TAG_BY_ROLE[role]!;
  switch (node.type) {
    case 'text':
      return 'span';
    case 'image':
      return 'img';
    case 'button':
      return 'button';
    case 'input':
      return 'input';
    case 'list':
      return 'ul';
    case 'list-item':
      return 'li';
    default:
      return 'div';
  }
}

function escapeJsxText(s: string): string {
  return s.replace(/\{/g, '&#123;').replace(/\}/g, '&#125;').replace(/</g, '&lt;');
}

export class ReactGenerator extends CodeGenerator {
  readonly platform = 'react';

  generate(doc: IRDocument): GenerateResult {
    const componentName = pascalCase(doc.name || 'GeneratedComponent');
    const body = this.renderNode(doc.root, 4);
    const tsx = `// Generated by d2c — React + Tailwind CSS
import React from 'react';

export interface ${componentName}Props {
  className?: string;
}

export const ${componentName}: React.FC<${componentName}Props> = ({ className }) => {
  return (
${body}
  );
};

export default ${componentName};
`;
    return {
      entryFile: `${componentName}.tsx`,
      files: [{ path: `${componentName}.tsx`, content: tsx }],
    };
  }

  // 多页面：每页一个组件 + 一个带导航的 App 入口
  generateMultiPage(docs: IRDocument[]): GenerateResult {
    if (docs.length === 1) return this.generate(docs[0]);
    const files: { path: string; content: string }[] = [];
    const pageComponents: { name: string; file: string }[] = [];
    for (const doc of docs) {
      const result = this.generate(doc);
      for (const f of result.files) files.push(f);
      const compName = pascalCase(doc.name || 'GeneratedComponent');
      pageComponents.push({ name: compName, file: compName });
    }
    // 生成 App 入口组件
    const imports = pageComponents
      .map((p) => `import { ${p.name} } from './${p.file}';`)
      .join('\n');
    const navItems = pageComponents
      .map((p) => `        <button onClick={() => setPage('${p.name}')} className={page === '${p.name}' ? 'font-bold' : ''}>${p.name}</button>`)
      .join('\n');
    const pageSwitch = pageComponents
      .map((p) => `      {page === '${p.name}' && <${p.name} />}`)
      .join('\n');
    const appTsx = `// Generated by d2c — Multi-page App
import React, { useState } from 'react';
${imports}

const App: React.FC = () => {
  const [page, setPage] = useState('${pageComponents[0].name}');
  return (
    <div>
      <nav className="flex gap-4 p-3 bg-gray-100 border-b">
${navItems}
      </nav>
${pageSwitch}
    </div>
  );
};

export default App;
`;
    files.push({ path: 'App.tsx', content: appTsx });
    return { files, entryFile: 'App.tsx' };
  }

  private renderNode(node: IRNode, indent: number, parentLayout?: 'flex' | 'grid' | 'absolute'): string {
    const pad = ' '.repeat(indent);
    const tag = tagFor(node);
    const classes = this.twClasses(node, parentLayout);
    const classAttr = classes.length ? ` className="${classes.join(' ')}"` : '';

    if (node.type === 'image') {
      const src = node.assetRef ?? '';
      const alt = node.semantics?.ariaLabel ?? node.name;
      return `${pad}<img src="${src}" alt="${escapeJsxText(alt)}"${classAttr} />`;
    }
    if (node.type === 'input') {
      return `${pad}<input${classAttr} />`;
    }
    if (node.type === 'text' || node.textStyle) {
      const content = escapeJsxText(node.textStyle?.content ?? '');
      return `${pad}<${tag}${classAttr}>${content}</${tag}>`;
    }
    if (node.children.length === 0) {
      return `${pad}<${tag}${classAttr} />`;
    }
    const childLayout = node.layout.type;
    const children = node.children.map((c) => this.renderNode(c, indent + 2, childLayout)).join('\n');
    return `${pad}<${tag}${classAttr}>
${children}
${pad}</${tag}>`;
  }

  private twClasses(node: IRNode, parentLayout?: 'flex' | 'grid' | 'absolute'): string[] {
    const classes: string[] = [];
    const { box, layout, style, textStyle } = node;

    // Absolute-positioned child: add absolute + left/top
    if (parentLayout === 'absolute') {
      classes.push('absolute');
      if (box.x) classes.push(`left-[${Math.round(box.x)}px]`);
      if (box.y) classes.push(`top-[${Math.round(box.y)}px]`);
    }

    // Layout
    if (layout.type === 'flex') {
      classes.push('flex');
      if (layout.direction === 'column') classes.push('flex-col');
      if (layout.gap) classes.push(`gap-[${Math.round(layout.gap)}px]`);
      const aiMap: Record<string, string> = {
        start: 'items-start',
        center: 'items-center',
        end: 'items-end',
        stretch: 'items-stretch',
      };
      if (layout.alignItems) classes.push(aiMap[layout.alignItems]);
      const jcMap: Record<string, string> = {
        start: 'justify-start',
        center: 'justify-center',
        end: 'justify-end',
        'space-between': 'justify-between',
        'space-around': 'justify-around',
        'space-evenly': 'justify-evenly',
      };
      if (layout.justifyContent) classes.push(jcMap[layout.justifyContent]);
    } else if (layout.type === 'grid') {
      classes.push('grid');
      if (layout.columns) classes.push(`grid-cols-${layout.columns}`);
      if (layout.gap) classes.push(`gap-[${Math.round(layout.gap)}px]`);
    } else if (layout.type === 'absolute' && parentLayout !== 'absolute') {
      classes.push('relative');
    }

    // Size
    if (typeof box.width === 'number') classes.push(`w-[${Math.round(box.width)}px]`);
    else if (box.width === 'fill') classes.push('w-full');
    if (typeof box.height === 'number') classes.push(`h-[${Math.round(box.height)}px]`);
    else if (box.height === 'fill') classes.push('h-full');

    // Padding
    if (box.padding) {
      const [t, r, b, l] = box.padding;
      if (t === r && r === b && b === l) {
        if (t) classes.push(`p-[${t}px]`);
      } else {
        if (t) classes.push(`pt-[${t}px]`);
        if (r) classes.push(`pr-[${r}px]`);
        if (b) classes.push(`pb-[${b}px]`);
        if (l) classes.push(`pl-[${l}px]`);
      }
    }

    // Style
    if (style.backgroundColor) classes.push(`bg-[${style.backgroundColor}]`);
    if (typeof style.borderRadius === 'number')
      classes.push(`rounded-[${style.borderRadius}px]`);
    if (style.border)
      classes.push(
        `border-[${style.border.width}px]`,
        `border-[${style.border.color}]`,
      );
    if (style.opacity !== undefined && style.opacity < 1)
      classes.push(`opacity-[${style.opacity}]`);
    if (style.shadows && style.shadows.length) classes.push('shadow-md');

    // Text
    if (textStyle) {
      classes.push(`text-[${textStyle.fontSize}px]`);
      classes.push(`text-[${textStyle.color}]`);
      if (textStyle.fontWeight >= 700) classes.push('font-bold');
      else if (textStyle.fontWeight >= 600) classes.push('font-semibold');
      else if (textStyle.fontWeight >= 500) classes.push('font-medium');
      if (textStyle.lineHeight)
        classes.push(`leading-[${Math.round(textStyle.lineHeight)}px]`);
      if (textStyle.textAlign && textStyle.textAlign !== 'left')
        classes.push(`text-${textStyle.textAlign}`);
    }

    // Responsive breakpoint overrides → Tailwind prefixed classes
    if (node.responsive) {
      for (const [bp, overrides] of Object.entries(node.responsive)) {
        if (overrides.hidden) {
          classes.push(`${bp}:hidden`);
          continue;
        }
        if (overrides.box) {
          if (typeof overrides.box.width === 'number')
            classes.push(`${bp}:w-[${Math.round(overrides.box.width)}px]`);
          else if (overrides.box.width === 'fill') classes.push(`${bp}:w-full`);
          if (typeof overrides.box.height === 'number')
            classes.push(`${bp}:h-[${Math.round(overrides.box.height)}px]`);
          else if (overrides.box.height === 'fill') classes.push(`${bp}:h-full`);
          if (overrides.box.padding) {
            const [pt, pr, pb, pl] = overrides.box.padding;
            if (pt === pr && pr === pb && pb === pl) {
              if (pt) classes.push(`${bp}:p-[${pt}px]`);
            } else {
              if (pt) classes.push(`${bp}:pt-[${pt}px]`);
              if (pr) classes.push(`${bp}:pr-[${pr}px]`);
              if (pb) classes.push(`${bp}:pb-[${pb}px]`);
              if (pl) classes.push(`${bp}:pl-[${pl}px]`);
            }
          }
        }
        if (overrides.layout) {
          if (overrides.layout.direction === 'column') classes.push(`${bp}:flex-col`);
          else if (overrides.layout.direction === 'row') classes.push(`${bp}:flex-row`);
          if (overrides.layout.gap !== undefined)
            classes.push(`${bp}:gap-[${Math.round(overrides.layout.gap)}px]`);
        }
        if (overrides.textStyle) {
          if (overrides.textStyle.fontSize)
            classes.push(`${bp}:text-[${overrides.textStyle.fontSize}px]`);
          if (overrides.textStyle.color)
            classes.push(`${bp}:text-[${overrides.textStyle.color}]`);
        }
        if (overrides.style) {
          if (overrides.style.backgroundColor)
            classes.push(`${bp}:bg-[${overrides.style.backgroundColor}]`);
        }
      }
    }

    return classes;
  }
}
