/**
 * Vue 3 SFC generator with scoped CSS.
 */
import type { IRDocument, IRNode, SemanticRole } from '../ir/types';
import { CodeGenerator, GenerateResult } from './base';
import { buildCssProps, cssPropsToBlock } from './cssBuilder';
import { pascalCase, kebabCase } from '../utils/tree';

const HTML_TAG_BY_ROLE: Partial<Record<SemanticRole, string>> = {
  header: 'header',
  nav: 'nav',
  footer: 'footer',
  main: 'main',
  aside: 'aside',
  section: 'section',
  card: 'article',
  list: 'ul',
  'list-item': 'li',
  button: 'button',
  link: 'a',
  heading: 'h2',
  paragraph: 'p',
  label: 'label',
};

function tagFor(node: IRNode): string {
  const role = node.semantics?.role;
  if (role && HTML_TAG_BY_ROLE[role]) return HTML_TAG_BY_ROLE[role]!;
  switch (node.type) {
    case 'text': return 'span';
    case 'image': return 'img';
    case 'button': return 'button';
    case 'input': return 'input';
    case 'list': return 'ul';
    case 'list-item': return 'li';
    default: return 'div';
  }
}

export class VueGenerator extends CodeGenerator {
  readonly platform = 'vue';
  private classIndex = new Map<string, string>();
  private classCss: string[] = [];
  private counter = 0;

  generate(doc: IRDocument): GenerateResult {
    this.classIndex.clear();
    this.classCss = [];
    this.counter = 0;

    const componentName = pascalCase(doc.name || 'GeneratedComponent');
    const template = this.renderNode(doc.root, 2);

    const sfc = `<!-- Generated by d2c -->
<template>
${template}
</template>

<script setup lang="ts">
defineProps<{ className?: string }>();
</script>

<style scoped>
${this.classCss.join('\n\n')}
</style>
`;

    return {
      entryFile: `${componentName}.vue`,
      files: [{ path: `${componentName}.vue`, content: sfc }],
    };
  }

  // 多页面：每页一个 SFC + 一个带导航的 App.vue 入口
  generateMultiPage(docs: IRDocument[]): GenerateResult {
    if (docs.length === 1) return this.generate(docs[0]);
    const files: { path: string; content: string }[] = [];
    const pageComponents: { name: string; file: string }[] = [];
    for (const doc of docs) {
      const result = this.generate(doc);
      for (const f of result.files) files.push(f);
      const compName = pascalCase(doc.name || 'GeneratedComponent');
      pageComponents.push({ name: compName, file: `${compName}.vue` });
    }
    const imports = pageComponents
      .map((p) => `import ${p.name} from './${p.file}';`)
      .join('\n');
    const buttons = pageComponents
      .map((p) => `      <button @click="page = '${p.name}'" :style="page === '${p.name}' ? {fontWeight:'bold'} : {}">${p.name}</button>`)
      .join('\n');
    const comps = pageComponents
      .map((p) => `    <${p.name} v-if="page === '${p.name}'" />`)
      .join('\n');
    const appSfc = `<!-- Generated by d2c — Multi-page App -->
<template>
  <div>
    <nav style="display:flex;gap:16px;padding:12px 16px;background:#f5f5f5;border-bottom:1px solid #ddd">
${buttons}
    </nav>
${comps}
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
${imports}

const page = ref('${pageComponents[0].name}');
</script>
`;
    files.push({ path: 'App.vue', content: appSfc });
    return { files, entryFile: 'App.vue' };
  }

  private classFor(node: IRNode, parentLayout?: 'flex' | 'grid' | 'absolute'): string {
    const props = buildCssProps(node, parentLayout);
    const key = JSON.stringify(props);
    if (this.classIndex.has(key)) return this.classIndex.get(key)!;
    const base = kebabCase(node.semantics?.componentName || node.name || node.type);
    const name = `${base}-${++this.counter}`;
    this.classIndex.set(key, name);
    this.classCss.push(`.${name} {\n${cssPropsToBlock(props, 2)}\n}`);
    return name;
  }

  private renderNode(node: IRNode, indent: number, parentLayout?: 'flex' | 'grid' | 'absolute'): string {
    const pad = ' '.repeat(indent);
    const tag = tagFor(node);
    const className = this.classFor(node, parentLayout);

    if (node.type === 'image') {
      const src = node.assetRef ?? '';
      const alt = node.semantics?.ariaLabel ?? node.name;
      return `${pad}<img class="${className}" src="${src}" alt="${alt}" />`;
    }
    if (node.type === 'text' || node.textStyle) {
      const content = this.escapeText(node.textStyle?.content ?? '');
      return `${pad}<${tag} class="${className}">${content}</${tag}>`;
    }
    if (node.children.length === 0) {
      return `${pad}<${tag} class="${className}"></${tag}>`;
    }
    const childLayout = node.layout.type;
    const children = node.children.map((c) => this.renderNode(c, indent + 2, childLayout)).join('\n');
    return `${pad}<${tag} class="${className}">
${children}
${pad}</${tag}>`;
  }
}
