/**
 * Vue 3 SFC generator with scoped CSS.
 */
import type { IRDocument, IRNode, SemanticRole } from '../ir/types';
import { CodeGenerator, GenerateResult } from './base';
import { buildCssProps, cssPropsToBlock } from './cssBuilder';
import { pascalCase, kebabCase } from '../utils/tree';

const HTML_TAG_BY_ROLE: Partial<Record<SemanticRole, string>> = {
  header: 'header',
  nav: 'nav',
  footer: 'footer',
  main: 'main',
  aside: 'aside',
  section: 'section',
  card: 'article',
  list: 'ul',
  'list-item': 'li',
  button: 'button',
  link: 'a',
  heading: 'h2',
  paragraph: 'p',
};

function tagFor(node: IRNode): string {
  const role = node.semantics?.role;
  if (role && HTML_TAG_BY_ROLE[role]) return HTML_TAG_BY_ROLE[role]!;
  switch (node.type) {
    case 'text': return 'span';
    case 'image': return 'img';
    case 'button': return 'button';
    case 'input': return 'input';
    case 'list': return 'ul';
    case 'list-item': return 'li';
    default: return 'div';
  }
}

export class VueGenerator extends CodeGenerator {
  readonly platform = 'vue';
  private classIndex = new Map<string, string>();
  private classCss: string[] = [];
  private counter = 0;

  generate(doc: IRDocument): GenerateResult {
    this.classIndex.clear();
    this.classCss = [];
    this.counter = 0;

    const componentName = pascalCase(doc.name || 'GeneratedComponent');
    const template = this.renderNode(doc.root, 2);

    const sfc = `<!-- Generated by d2c -->
<template>
${template}
</template>

<script setup lang="ts">
defineProps<{ className?: string }>();
</script>

<style scoped>
${this.classCss.join('\n\n')}
</style>
`;

    return {
      entryFile: `${componentName}.vue`,
      files: [{ path: `${componentName}.vue`, content: sfc }],
    };
  }

  private classFor(node: IRNode): string {
    const props = buildCssProps(node);
    const key = JSON.stringify(props);
    if (this.classIndex.has(key)) return this.classIndex.get(key)!;
    const base = kebabCase(node.semantics?.componentName || node.name || node.type);
    const name = `${base}-${++this.counter}`;
    this.classIndex.set(key, name);
    this.classCss.push(`.${name} {\n${cssPropsToBlock(props, 2)}\n}`);
    return name;
  }

  private renderNode(node: IRNode, indent: number): string {
    const pad = ' '.repeat(indent);
    const tag = tagFor(node);
    const className = this.classFor(node);

    if (node.type === 'image') {
      const src = node.assetRef ?? '';
      const alt = node.semantics?.ariaLabel ?? node.name;
      return `${pad}<img class="${className}" src="${src}" alt="${alt}" />`;
    }
    if (node.type === 'text' || node.textStyle) {
      const content = this.escapeText(node.textStyle?.content ?? '');
      return `${pad}<${tag} class="${className}">${content}</${tag}>`;
    }
    if (node.children.length === 0) {
      return `${pad}<${tag} class="${className}"></${tag}>`;
    }
    const children = node.children.map((c) => this.renderNode(c, indent + 2)).join('\n');
    return `${pad}<${tag} class="${className}">
${children}
${pad}</${tag}>`;
  }
}
