/**
 * Tailwind preset / theme generator (P1).
 *
 * Converts a `TokenSet` into a `tailwind.config.js` preset that projects
 * can `extend`. The goal is that downstream React/Vue output can stop
 * using arbitrary-value classes like `bg-[#0f172a]` in favor of
 * semantic tokens like `bg-slate-900`.
 */
import type { TokenSet } from './extract';

function toPx(n: number): string {
  return `${n}px`;
}

function quoted(s: string): string {
  return `'${s.replace(/'/g, "\\'")}'`;
}

function indent(s: string, n: number): string {
  const pad = ' '.repeat(n);
  return s
    .split('\n')
    .map((l) => (l.length ? pad + l : l))
    .join('\n');
}

function renderObject(obj: Record<string, string>): string {
  if (Object.keys(obj).length === 0) return '{}';
  const lines = Object.entries(obj).map(
    ([k, v]) => `${quoted(k)}: ${quoted(v)},`,
  );
  return `{\n${indent(lines.join('\n'), 2)}\n}`;
}

export function generateTailwindPreset(tokens: TokenSet): string {
  const colors = { ...tokens.colors };
  const fontSize: Record<string, string> = {};
  for (const [k, v] of Object.entries(tokens.fontSizes)) fontSize[k] = toPx(v);
  const spacing: Record<string, string> = {};
  for (const [k, v] of Object.entries(tokens.spacings)) spacing[k] = toPx(v);
  const borderRadius: Record<string, string> = {};
  for (const [k, v] of Object.entries(tokens.radii)) borderRadius[k] = toPx(v);
  const boxShadow: Record<string, string> = { ...tokens.shadows };
  const fontWeight: Record<string, string> = {};
  for (const [k, v] of Object.entries(tokens.fontWeights))
    fontWeight[k] = String(v);

  return `/** Generated by d2c — Tailwind preset */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: ${indent(renderObject(colors), 6).trimStart()},
      fontSize: ${indent(renderObject(fontSize), 6).trimStart()},
      fontWeight: ${indent(renderObject(fontWeight), 6).trimStart()},
      spacing: ${indent(renderObject(spacing), 6).trimStart()},
      borderRadius: ${indent(renderObject(borderRadius), 6).trimStart()},
      boxShadow: ${indent(renderObject(boxShadow), 6).trimStart()},
    },
  },
};
`;
}

/**
 * Build reverse lookups for token values → token class names. Used by the
 * React generator to swap arbitrary-value classes for token classes when a
 * preset is supplied.
 */
export interface TailwindTokenLookup {
  color(css: string): string | undefined;
  fontSize(px: number): string | undefined;
  spacing(px: number): string | undefined;
  radius(px: number): string | undefined;
}

export function buildTailwindLookup(tokens: TokenSet): TailwindTokenLookup {
  const colorRev = new Map<string, string>();
  for (const [k, v] of Object.entries(tokens.colors)) {
    colorRev.set(v.toLowerCase(), k);
  }
  const fs = new Map<number, string>();
  for (const [k, v] of Object.entries(tokens.fontSizes)) fs.set(v, k);
  const sp = new Map<number, string>();
  for (const [k, v] of Object.entries(tokens.spacings)) sp.set(v, k);
  const rd = new Map<number, string>();
  for (const [k, v] of Object.entries(tokens.radii)) rd.set(v, k);
  return {
    color: (css) => colorRev.get(css.toLowerCase()),
    fontSize: (p) => fs.get(p),
    spacing: (p) => sp.get(p),
    radius: (p) => rd.get(p),
  };
}
